sinsistem/sinsistem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('teachers/', include(('teachers.urls', 'teachers'), namespace='teachers')),
]

urlpatterns += staticfiles_urlpatterns()

sinsistem/teachers/urls.py
from django.contrib import admin
from django.urls import path, include
from teachers import views
app_name = 'teachers'
from .views import (
    teacher_login,
    register,
    index,
    logout
)
urlpatterns = [
    path('teacher_login/', teacher_login, name='teacher_login'),
    path('register/', register, name='register'),
    path('index/', views.index, name='index'),
    path('create_question/', views.create_question, name='create_question'),
    path('^logout/', views.teacher_logout, name='logout'),
    ]

sinsistem/teachers/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Teacher(models.Model):
    teacher = models.OneToOneField(User, on_delete=models.CASCADE, default=1)
    first_name = models.CharField(max_length=120)
    last_name = models.CharField(max_length=120)
    title = models.CharField(max_length=120)
    about = models.TextField()

    def __str__(self):
        return self.teacher.username

    def get_absolute_url(self):
        return reverse("teachers:index", kwargs={"id": self.id})

class Lesson(models.Model):
    prof = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    lesson_name = models.CharField(max_length=120)
    lesson_description = models.TextField()

    def __str__(self):
        return self.lesson_name

class Subject(models.Model):
    ders = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    subject_name = models.CharField(max_length=120)
    subject_description = models.TextField()

    def __str__(self):
        return self.subject_name

class Question(models.Model):
    konu = models.ForeignKey(Subject, on_delete=models.CASCADE)
    question_description = models.TextField()
    question_answer = models.TextField()
    question_point = models.IntegerField()
    question_time = models.TimeField()
    question_date = models.DateField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.question_description

sinsistem/teachers/forms.py
from random import choices
from django import forms
from .models import Teacher, Lesson, Subject, Question
from django.contrib.auth.models import User

class TeacherForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ["username", "password", "email"]

class TeacherProfileForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ["first_name", "last_name", "title", "about"]

class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ["lesson_name"]

class AllLessonForm(forms.ModelForm):
    all_lessons = forms.ModelChoiceField(queryset=Lesson.objects.all())
    class Meta:
        model = Lesson
        fields = ["all_lessons"]

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ["subject_name"]

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ["question_description", "question_answer", "question_point", "question_time"]


        # widgets = {
        #     'question_date': forms.DateInput(attrs={'class': 'datepicker'})
        # }
    # def __init__(self, user, *args, **kwargs):
    #     super(LessonForm, self).__init__(*args, **kwargs)
    #     self.fields["lesson"] = forms.ChoiceField(choices=[(lesson.id, lesson.name) for lesson in Lesson.objects.all()])

sinsistem/teachers/views.py
from django.shortcuts import render, redirect
from .forms import TeacherForm, TeacherProfileForm, QuestionForm, LessonForm, SubjectForm
from .models import Lesson, Teacher, Question, Subject
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from urllib.parse import quote_plus

def index(request):
    instance = Lesson.objects.all()
    context = {
        "lesson_list": instance
    }
    return render(request, "teachers/index.html", context)

@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def teacher_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("teachers:index"))

def register(request):
    registered = False
    if request.method == "POST":
        teacher_form = TeacherForm(data=request.POST)
        profile_form = TeacherProfileForm(data=request.POST)
        if teacher_form.is_valid() and profile_form.is_valid():
            teacher = teacher_form.save()
            teacher.set_password(teacher.password)
            teacher.save()
            profile = profile_form.save(commit=False)
            profile.teacher = teacher
            profile.save()
            registered = True
        else:
            print(teacher_form.errors, profile_form.errors)
    else:
        teacher_form = TeacherForm()
        profile_form = TeacherProfileForm()
    return render(request, "teachers/registration.html",
                          {"teacher_form": teacher_form,
                           "profile_form": profile_form,
                           "registered": registered})

def teacher_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        teacher = authenticate(username=username, password=password)
        if teacher:
            if teacher.is_active:
                login(request, teacher)
                return HttpResponseRedirect(reverse("teachers:index"))
            else:
                return HttpResponse("Your account was inactive")
        else:
            print("Someone tried to login and failed")
            print("They used username: {} and password: {}".format(username, password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, "teachers/login.html", {})

def create_question(request):
    created = False
    if request.method == "POST":
        lesson_form = LessonForm(data=request.POST)
        subject_form = SubjectForm(data=request.POST)
        question_form = QuestionForm(data=request.POST)
        if question_form.is_valid() and lesson_form.is_valid() and subject_form.is_valid():
            question = question_form.save()
            question.save()
            lesson = lesson_form.save()
            lesson.save()
            subject = subject_form.save()
            subject.save()
            created = True
            messages.success(request, "Successfully Created!!!")
        else:
            print(question_form.errors, lesson_form.errors, subject_form.errors)
    else:
        question_form = QuestionForm()
        lesson_form = LessonForm()
        subject_form = SubjectForm()
    all_lessons = Lesson.objects.all()
    all_subjects = Subject.objects.all()
    context = {
        "question_form": question_form,
        "lesson_form": lesson_form,
        "all_subjects": all_subjects,
        "created": created,
        "all_lessons": all_lessons,
                             }
    return render(request, "teachers/create_question.html", context)

# def get_lessons(request):
#     lesson = request.GET["selected_lesson"]
#     print(lesson)
#     result_set = []
#     all_subjects = []
#     answer = str(lesson[1:-1])
#     selected_lesson = Lesson.objects.get(lesson_name=answer)
#     all_lessons = selected_lesson.subject_set.all()
#     for sbj in all_subjects:
#         result_set.append({'subject_name': sbj.subject_name})
#     return HttpResponse(simplejson.dumps(result_set), mimetype='application/json', content_type='application/json')

sinsistem/templates/teachers/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <meta name="theme-color" content="#232323">
  <link rel="manifest" href="{% static 'manifest.json' %}">
  <link rel="prefetch" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700">
  <link rel="preload" href="{% static 'assets/js/site.min.js' %}" as="script">
  <link rel="preload" href="{% static 'assets/js/vendor.min.js' %}" as="script">
  <link rel="stylesheet" href="{% static 'assets/css/site.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/vendor.min.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/monokai-sublime.min.css">
   <meta name="msapplication-TileColor" content="#232323">
  <meta name="msapplication-TileImage" content="assets/img/ms-icon-144x144.png">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'teachers:index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'teachers:register' %}">Register</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'teachers:logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'teachers:teacher_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>

  <script>
jQuery($ => {
  $('.build-wrap').formBuilder()
})
</script>
  </body>
</html>

sinsistem/templates/teachers/create_question.html
{% extends "teachers/base.html" %}

{% block body_block %}
  {% load static from staticfiles %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Soru Oluşturma Formu</h1>
        <h3>Formu doldurunuz</h3>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
            <select class="form-control" id="lesson_name" name="selected_lesson">
              {% for lsn in all_lessons %}
              {% if lsn.prof.id == user.teacher.id %}
                <option value="{{ lsn.id }}"selected="selected">{{ lsn.lesson_name }}</option>
              {% endif %}
              {% endfor %}
            </select>
               <select class="form-control" id="subject_name" name="selected_lesson">
              {% for sbj in all_subjects %}
              {% if sbj.ders.id == 2 %}
                <option value="{{ sbj.id }}"selected="selected">{{ sbj.subject_name }}</option>
              {% endif %}
              {% endfor %}
            </select>
 <div id="fb-root"></div>
  <div class="site-wrap container">
    <div id="header_wrap" class="outer">

    </div>
    <!-- MAIN CONTENT -->
    <div id="main-content-wrap" class="outer">

      <br id="main_content" class="inner">
          <label for="soru1">Soru1</label>
      </br>
             <input type="radio" name="sorutype" > cok secenek </input>
                <input type="radio"  name="sorutype" > bosluk </input>
          </br>
       <input name="soru1" ></input>

  </br>
            <label for="soru1">cvpler</label>
          </br>
       <input name="cvp1" ></input>
 <input name="cvp2" ></input>
           <input name="cvp3" ></input>
           <input name="cvp4" ></input>

           </br>
          <label for="soru1">dorgu cvp</label>
             <input type="radio" name="1" > 1 </input>
                <input type="radio"  name="2" > 2 </input>
          </br>

      </section>
    </div>
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.0/clipboard.min.js"></script>

  <script src="{% static 'assets/js/vendor.min96ad.js' %}"></script>
  <script src="{% static 'assets/js/form-builder.min96ad.js' %}"></script>
  <script src="{% static 'assets/js/form-render.min96ad.js' %}"></script>
  <script src="{% static 'assets/js/site.min96ad.js' %}"></script>

          <input type="submit" name="" value="Oluştur">
        </form>
      {% endif %}
    </div>
  </div>
{% endblock %}

sinsistem/templates/teachers/index.html
{% extends "teachers/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <form method="post" action="{% url 'teachers:create_question' %}">
      {% csrf_token %}
    {% if user.is_authenticated %}
    <h1>HOŞ GELDİNİZ {{ user.teacher.teacher}}!</h1>
      <p>Eğitmenin adı ve soyadı: {{ user.teacher.first_name }} {{user.teacher.last_name}}</p>
      <p>Eğitmenin ünvanı: {{ user.teacher.title }}</p>
      <p>Eğitmen hakkında: {{ user.teacher.about }}</p>
        <p>Eğitmenin dersleri: {% for lesson in lesson_list %}
                                {% if user.teacher.id == lesson.prof.id %}
                                {{ lesson.lesson_name }}
                                {% endif %}
                                {% endfor %}
    </p>
    <input type="submit" name="" class="btn btn-default" value="Soru Oluştur">
    </form>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

sinsistem/templates/teachers/login.html
{% extends 'teachers/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'teachers:teacher_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

sinsistem/templates/teachers/registration.html
{% extends "teachers/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ teacher_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}
    </div>
  </div>
{% endblock %}